//! Per-skin token tables.
//!
//! This is a static table: five skins x two colour schemes, one explicit
//! `Palette` literal each, kept in one place so every shipped surface can be
//! audited side by side (the file-length exception in `AGENTS.md` 3.2
//! covers static resource tables). Behaviour lives in `palette/mod.rs`.

use super::Palette;
use super::tint;
use crate::components::style::tokens::{
    AccentId, AccentTokens, ColorScheme, ColorToken, Shape, SkinId,
};

pub(super) const fn tokens(scheme: ColorScheme, accent: AccentId, skin: SkinId) -> Palette {
    let accent_tokens = AccentTokens::for_scheme(accent, scheme);
    let shape = Shape::for_skin(skin);
    let decor = skin.decor();
    let decor_line = accent_tokens.decor;
    let glow = tint(decor_line, 0x3d);
    match (skin, scheme) {
        // ---------------------------------------------------------------
        // Limbus — cold black with dark-red rivets and a brass frame.
        // Keeps the pre-existing dark values byte for byte.
        // ---------------------------------------------------------------
        (SkinId::Limbus, ColorScheme::Dark) => Palette {
            scheme,
            accent,
            skin,
            background: ColorToken::rgb(0x0b0a0e),
            foreground: ColorToken::rgb(0xd8d0bc),
            card: ColorToken::rgb(0x1b1114),
            card_foreground: ColorToken::rgb(0xd8d0bc),
            popover: ColorToken::rgb(0x241619),
            popover_foreground: ColorToken::rgb(0xd8d0bc),
            primary: ColorToken::rgb(0xd8d0bc),
            primary_foreground: ColorToken::rgb(0x14090a),
            secondary: ColorToken::rgb(0x2a1b1e),
            secondary_foreground: ColorToken::rgb(0xd8d0bc),
            muted: ColorToken::rgb(0x241619),
            muted_foreground: ColorToken::rgb(0xb3a68a),
            accent_surface: ColorToken::rgb(0x3a2023),
            accent_foreground: decor_line,
            destructive: ColorToken::rgb(0xff6467),
            border: ColorToken::rgb(0x462c2c),
            input: ColorToken::rgb(0x6b4a1a),
            ring: decor_line,
            success: ColorToken::rgb(0x4cdb7c),
            success_light: ColorToken::rgb(0x0c341e),
            warning: ColorToken::rgb(0xe8c43c),
            warning_light: ColorToken::rgb(0x3a2e14),
            danger: ColorToken::rgb(0xb92828),
            danger_light: ColorToken::rgb(0x3a1414),
            danger_foreground: ColorToken::rgb(0xf6e8e8),
            selection: tint(decor_line, 0x33),
            scrim: ColorToken::rgba(0x07060ae6),
            decor_line,
            hilite: ColorToken::rgba(0x00000000),
            glow: ColorToken::rgba(0x00000000),
            brand: accent_tokens.brand,
            brand_hover: accent_tokens.brand_hover,
            brand_light: accent_tokens.brand_light,
            brand_foreground: accent_tokens.brand_foreground,
            shape,
            decor,
        },
        // Limbus light: parchment archive paper with oxblood ink and a
        // bronze rule. Same square geometry and bracket language.
        (SkinId::Limbus, ColorScheme::Light) => Palette {
            scheme,
            accent,
            skin,
            background: ColorToken::rgb(0xece3d2),
            foreground: ColorToken::rgb(0x241211),
            card: ColorToken::rgb(0xf6efe1),
            card_foreground: ColorToken::rgb(0x241211),
            popover: ColorToken::rgb(0xfbf6ea),
            popover_foreground: ColorToken::rgb(0x241211),
            primary: ColorToken::rgb(0x2a1512),
            primary_foreground: ColorToken::rgb(0xf6efe1),
            secondary: ColorToken::rgb(0xe2d7c1),
            secondary_foreground: ColorToken::rgb(0x241211),
            muted: ColorToken::rgb(0xe6dcc8),
            muted_foreground: ColorToken::rgb(0x6b5a42),
            accent_surface: ColorToken::rgb(0xd9cbb0),
            // On parchment the header title is oxblood ink; the bronze
            // frame tone stays on rules and brackets only.
            accent_foreground: ColorToken::rgb(0x241211),
            destructive: ColorToken::rgb(0x9b1c1c),
            border: ColorToken::rgb(0xc9b795),
            input: ColorToken::rgb(0xb9a37c),
            ring: decor_line,
            success: ColorToken::rgb(0x14713f),
            success_light: ColorToken::rgb(0xdcefe2),
            warning: ColorToken::rgb(0x8a5a10),
            warning_light: ColorToken::rgb(0xf6e6c8),
            danger: ColorToken::rgb(0x9b1c1c),
            danger_light: ColorToken::rgb(0xf3dcdc),
            danger_foreground: ColorToken::rgb(0xfdf7ec),
            selection: tint(decor_line, 0x33),
            scrim: ColorToken::rgba(0x241211b8),
            decor_line,
            hilite: ColorToken::rgba(0x00000000),
            glow: ColorToken::rgba(0x00000000),
            brand: accent_tokens.brand,
            brand_hover: accent_tokens.brand_hover,
            brand_light: accent_tokens.brand_light,
            brand_foreground: accent_tokens.brand_foreground,
            shape,
            decor,
        },
        // ---------------------------------------------------------------
        // Glass — layered translucency over a tinted ground.
        // ---------------------------------------------------------------
        (SkinId::Glass, ColorScheme::Dark) => Palette {
            scheme,
            accent,
            skin,
            background: ColorToken::rgb(0x0a0d14),
            foreground: ColorToken::rgb(0xeef2f8),
            card: ColorToken::rgba(0xffffff14),
            card_foreground: ColorToken::rgb(0xeef2f8),
            popover: ColorToken::rgba(0x161b24fa),
            popover_foreground: ColorToken::rgb(0xeef2f8),
            primary: ColorToken::rgb(0xeef2f8),
            primary_foreground: ColorToken::rgb(0x0a0d14),
            secondary: ColorToken::rgba(0xffffff1f),
            secondary_foreground: ColorToken::rgb(0xeef2f8),
            muted: ColorToken::rgba(0xffffff0f),
            muted_foreground: ColorToken::rgb(0x9fb0c6),
            accent_surface: ColorToken::rgba(0xffffff29),
            accent_foreground: ColorToken::rgb(0xeef2f8),
            destructive: ColorToken::rgb(0xff6b6f),
            border: ColorToken::rgba(0xffffff24),
            input: ColorToken::rgba(0xffffff26),
            ring: decor_line,
            success: ColorToken::rgb(0x4cdb7c),
            success_light: ColorToken::rgba(0x4cdb7c26),
            warning: ColorToken::rgb(0xe8c43c),
            warning_light: ColorToken::rgba(0xe8c43c26),
            danger: ColorToken::rgb(0xff6b6f),
            danger_light: ColorToken::rgba(0xff6b6f26),
            danger_foreground: ColorToken::rgb(0x2a0a0c),
            selection: tint(decor_line, 0x33),
            scrim: ColorToken::rgba(0x05070cc7),
            decor_line,
            hilite: ColorToken::rgba(0xffffff33),
            glow,
            brand: accent_tokens.brand,
            brand_hover: accent_tokens.brand_hover,
            brand_light: accent_tokens.brand_light,
            brand_foreground: accent_tokens.brand_foreground,
            shape,
            decor,
        },
        (SkinId::Glass, ColorScheme::Light) => Palette {
            scheme,
            accent,
            skin,
            background: ColorToken::rgb(0xe9eef6),
            foreground: ColorToken::rgb(0x101828),
            card: ColorToken::rgba(0xffffffcc),
            card_foreground: ColorToken::rgb(0x101828),
            popover: ColorToken::rgba(0xfffffff2),
            popover_foreground: ColorToken::rgb(0x101828),
            primary: ColorToken::rgb(0x101828),
            primary_foreground: ColorToken::rgb(0xffffff),
            secondary: ColorToken::rgba(0x1018280f),
            secondary_foreground: ColorToken::rgb(0x101828),
            muted: ColorToken::rgba(0x1018280a),
            muted_foreground: ColorToken::rgb(0x5a6b82),
            accent_surface: ColorToken::rgba(0x10182814),
            accent_foreground: ColorToken::rgb(0x101828),
            destructive: ColorToken::rgb(0xd4182c),
            border: ColorToken::rgba(0x10182824),
            input: ColorToken::rgba(0x1018281f),
            ring: decor_line,
            success: ColorToken::rgb(0x0f8a45),
            success_light: ColorToken::rgba(0x0f8a4526),
            warning: ColorToken::rgb(0xb26a10),
            warning_light: ColorToken::rgba(0xb26a1026),
            danger: ColorToken::rgb(0xd4182c),
            danger_light: ColorToken::rgba(0xd4182c26),
            danger_foreground: ColorToken::rgb(0xffffff),
            selection: tint(decor_line, 0x33),
            scrim: ColorToken::rgba(0x10182880),
            decor_line,
            hilite: ColorToken::rgba(0xffffffcc),
            glow,
            brand: accent_tokens.brand,
            brand_hover: accent_tokens.brand_hover,
            brand_light: accent_tokens.brand_light,
            brand_foreground: accent_tokens.brand_foreground,
            shape,
            decor,
        },
        // ---------------------------------------------------------------
        // Archive — paper, ink and hairlines. No shadows at all.
        // ---------------------------------------------------------------
        (SkinId::Archive, ColorScheme::Light) => Palette {
            scheme,
            accent,
            skin,
            background: ColorToken::rgb(0xfbfaf7),
            foreground: ColorToken::rgb(0x16161a),
            card: ColorToken::rgb(0xffffff),
            card_foreground: ColorToken::rgb(0x16161a),
            popover: ColorToken::rgb(0xffffff),
            popover_foreground: ColorToken::rgb(0x16161a),
            primary: ColorToken::rgb(0x1c1c22),
            primary_foreground: ColorToken::rgb(0xfbfaf7),
            secondary: ColorToken::rgb(0xf1efe9),
            secondary_foreground: ColorToken::rgb(0x1c1c22),
            muted: ColorToken::rgb(0xf4f2ec),
            muted_foreground: ColorToken::rgb(0x6b6a63),
            accent_surface: ColorToken::rgb(0xeceae2),
            accent_foreground: ColorToken::rgb(0x1c1c22),
            destructive: ColorToken::rgb(0xa8181f),
            border: ColorToken::rgb(0xdedacd),
            input: ColorToken::rgb(0xdedacd),
            ring: decor_line,
            success: ColorToken::rgb(0x1a6b3c),
            success_light: ColorToken::rgb(0xe2efe5),
            warning: ColorToken::rgb(0x8a5a10),
            warning_light: ColorToken::rgb(0xf5e9d2),
            danger: ColorToken::rgb(0xa8181f),
            danger_light: ColorToken::rgb(0xf7e3e3),
            danger_foreground: ColorToken::rgb(0xffffff),
            selection: tint(decor_line, 0x2e),
            scrim: ColorToken::rgba(0x16161a99),
            decor_line,
            hilite: ColorToken::rgba(0x00000000),
            glow: ColorToken::rgba(0x00000000),
            brand: accent_tokens.brand,
            brand_hover: accent_tokens.brand_hover,
            brand_light: accent_tokens.brand_light,
            brand_foreground: accent_tokens.brand_foreground,
            shape,
            decor,
        },
        (SkinId::Archive, ColorScheme::Dark) => Palette {
            scheme,
            accent,
            skin,
            background: ColorToken::rgb(0x121215),
            foreground: ColorToken::rgb(0xe8e6e0),
            card: ColorToken::rgb(0x1a1a1f),
            card_foreground: ColorToken::rgb(0xe8e6e0),
            popover: ColorToken::rgb(0x212127),
            popover_foreground: ColorToken::rgb(0xe8e6e0),
            primary: ColorToken::rgb(0xe8e6e0),
            primary_foreground: ColorToken::rgb(0x16161a),
            secondary: ColorToken::rgb(0x24242b),
            secondary_foreground: ColorToken::rgb(0xe8e6e0),
            muted: ColorToken::rgb(0x1f1f25),
            muted_foreground: ColorToken::rgb(0x9a978e),
            accent_surface: ColorToken::rgb(0x2c2c34),
            accent_foreground: ColorToken::rgb(0xe8e6e0),
            destructive: ColorToken::rgb(0xff6467),
            border: ColorToken::rgb(0x2e2e36),
            input: ColorToken::rgb(0x33333c),
            ring: decor_line,
            success: ColorToken::rgb(0x4cdb7c),
            success_light: ColorToken::rgb(0x12301f),
            warning: ColorToken::rgb(0xe8c43c),
            warning_light: ColorToken::rgb(0x33290f),
            danger: ColorToken::rgb(0xff6467),
            danger_light: ColorToken::rgb(0x3a1616),
            danger_foreground: ColorToken::rgb(0x2a0a0c),
            selection: tint(decor_line, 0x33),
            scrim: ColorToken::rgba(0x05050ac7),
            decor_line,
            hilite: ColorToken::rgba(0x00000000),
            glow: ColorToken::rgba(0x00000000),
            brand: accent_tokens.brand,
            brand_hover: accent_tokens.brand_hover,
            brand_light: accent_tokens.brand_light,
            brand_foreground: accent_tokens.brand_foreground,
            shape,
            decor,
        },
        // ---------------------------------------------------------------
        // Mist — near black, red vignette, accent only on active states.
        // ---------------------------------------------------------------
        (SkinId::Mist, ColorScheme::Dark) => Palette {
            scheme,
            accent,
            skin,
            background: ColorToken::rgb(0x07060a),
            foreground: ColorToken::rgb(0xebe3d8),
            card: ColorToken::rgb(0x120e12),
            card_foreground: ColorToken::rgb(0xebe3d8),
            popover: ColorToken::rgb(0x1c161a),
            popover_foreground: ColorToken::rgb(0xebe3d8),
            primary: ColorToken::rgb(0xebe3d8),
            primary_foreground: ColorToken::rgb(0x140a0c),
            secondary: ColorToken::rgb(0x241a1e),
            secondary_foreground: ColorToken::rgb(0xebe3d8),
            muted: ColorToken::rgb(0x1c1519),
            muted_foreground: ColorToken::rgb(0xa08c8a),
            accent_surface: ColorToken::rgb(0x301c20),
            accent_foreground: decor_line,
            destructive: ColorToken::rgb(0xff5a5f),
            border: ColorToken::rgb(0x3a1f22),
            input: ColorToken::rgb(0x4a2620),
            ring: decor_line,
            success: ColorToken::rgb(0x3fd07a),
            success_light: ColorToken::rgb(0x0d2a1a),
            warning: ColorToken::rgb(0xe8b23c),
            warning_light: ColorToken::rgb(0x33260d),
            danger: ColorToken::rgb(0xff5a5f),
            danger_light: ColorToken::rgb(0x3d1214),
            danger_foreground: ColorToken::rgb(0x1a0608),
            selection: tint(decor_line, 0x33),
            scrim: ColorToken::rgba(0x05040ad9),
            decor_line,
            hilite: ColorToken::rgba(0x00000000),
            glow: ColorToken::rgba(0x00000000),
            brand: accent_tokens.brand,
            brand_hover: accent_tokens.brand_hover,
            brand_light: accent_tokens.brand_light,
            brand_foreground: accent_tokens.brand_foreground,
            shape,
            decor,
        },
        (SkinId::Mist, ColorScheme::Light) => Palette {
            scheme,
            accent,
            skin,
            background: ColorToken::rgb(0xf3eeea),
            foreground: ColorToken::rgb(0x221418),
            card: ColorToken::rgb(0xfdf9f6),
            card_foreground: ColorToken::rgb(0x221418),
            popover: ColorToken::rgb(0xffffff),
            popover_foreground: ColorToken::rgb(0x221418),
            primary: ColorToken::rgb(0x2a1418),
            primary_foreground: ColorToken::rgb(0xfdf9f6),
            secondary: ColorToken::rgb(0xece4de),
            secondary_foreground: ColorToken::rgb(0x221418),
            muted: ColorToken::rgb(0xefe7e1),
            muted_foreground: ColorToken::rgb(0x6f5f5c),
            accent_surface: ColorToken::rgb(0xe6d8d2),
            accent_foreground: decor_line,
            destructive: ColorToken::rgb(0xb81b22),
            border: ColorToken::rgb(0xdbcbc5),
            input: ColorToken::rgb(0xc9b4ad),
            ring: decor_line,
            success: ColorToken::rgb(0x18704a),
            success_light: ColorToken::rgb(0xdceee4),
            warning: ColorToken::rgb(0x8a5a10),
            warning_light: ColorToken::rgb(0xf6e7ce),
            danger: ColorToken::rgb(0xb81b22),
            danger_light: ColorToken::rgb(0xf6dedb),
            danger_foreground: ColorToken::rgb(0xffffff),
            selection: tint(decor_line, 0x33),
            scrim: ColorToken::rgba(0x2214188c),
            decor_line,
            hilite: ColorToken::rgba(0x00000000),
            glow: ColorToken::rgba(0x00000000),
            brand: accent_tokens.brand,
            brand_hover: accent_tokens.brand_hover,
            brand_light: accent_tokens.brand_light,
            brand_foreground: accent_tokens.brand_foreground,
            shape,
            decor,
        },
        // ---------------------------------------------------------------
        // Default — the flat shadcn/Radix look the web client defined.
        // Only the dark border changed: it used to be fully transparent,
        // which left dark-mode cards with no outline at all.
        // ---------------------------------------------------------------
        (SkinId::Default, ColorScheme::Light) => Palette {
            scheme,
            accent,
            skin,
            // oklch(0.963 0.003 25)
            background: ColorToken::rgb(0xf5f2f2),
            // oklch(0.145 0 0)
            foreground: ColorToken::rgb(0x0a0a0a),
            card: ColorToken::rgb(0xffffff),
            card_foreground: ColorToken::rgb(0x0a0a0a),
            popover: ColorToken::rgb(0xffffff),
            popover_foreground: ColorToken::rgb(0x0a0a0a),
            primary: ColorToken::rgb(0x171717),
            primary_foreground: ColorToken::rgb(0xfafafa),
            secondary: ColorToken::rgb(0xf5f5f5),
            secondary_foreground: ColorToken::rgb(0x171717),
            muted: ColorToken::rgb(0xf5f5f5),
            // Darkened from 0x737373 to reach 4.5:1 on the light ground.
            muted_foreground: ColorToken::rgb(0x6b6b6b),
            accent_surface: ColorToken::rgb(0xf5f5f5),
            accent_foreground: ColorToken::rgb(0x171717),
            destructive: ColorToken::rgb(0xe7000b),
            // --border is transparent in the browser; controls use --input.
            border: ColorToken::rgba(0x00000000),
            input: ColorToken::rgb(0xd9d9d9),
            ring: ColorToken::rgb(0xa1a1a1),
            success: ColorToken::rgb(0x18a349),
            success_light: ColorToken::rgb(0xdcfce6),
            warning: ColorToken::rgb(0xd6791d),
            warning_light: ColorToken::rgb(0xfff4cb),
            danger: ColorToken::rgb(0xe7000b),
            danger_light: ColorToken::rgb(0xfee2e2),
            danger_foreground: ColorToken::rgb(0xffffff),
            selection: ColorToken::rgba(0xc8354f33),
            scrim: ColorToken::rgba(0x0a0a0a80),
            decor_line: ColorToken::rgb(0xa1a1a1),
            hilite: ColorToken::rgba(0x00000000),
            glow: ColorToken::rgba(0x00000000),
            brand: accent_tokens.brand,
            brand_hover: accent_tokens.brand_hover,
            brand_light: accent_tokens.brand_light,
            brand_foreground: accent_tokens.brand_foreground,
            shape,
            decor,
        },
        (SkinId::Default, ColorScheme::Dark) => Palette {
            scheme,
            accent,
            skin,
            // oklch(0.135 0.005 25)
            background: ColorToken::rgb(0x0a0707),
            // oklch(0.985 0 0)
            foreground: ColorToken::rgb(0xfafafa),
            card: ColorToken::rgb(0x181515),
            card_foreground: ColorToken::rgb(0xfafafa),
            popover: ColorToken::rgb(0x262626),
            popover_foreground: ColorToken::rgb(0xfafafa),
            primary: ColorToken::rgb(0xe5e5e5),
            primary_foreground: ColorToken::rgb(0x171717),
            secondary: ColorToken::rgb(0x262626),
            secondary_foreground: ColorToken::rgb(0xfafafa),
            muted: ColorToken::rgb(0x262626),
            muted_foreground: ColorToken::rgb(0xa1a1a1),
            accent_surface: ColorToken::rgb(0x404040),
            accent_foreground: ColorToken::rgb(0xfafafa),
            destructive: ColorToken::rgb(0xff6467),
            // Was fully transparent, which left every dark-mode card
            // float without an outline. A 10% white rule restores the
            // surface hierarchy the web client had via its page tint.
            border: ColorToken::rgba(0xffffff1a),
            // oklch(1 0 0 / 15%) composited by GPUI at paint time.
            input: ColorToken::rgba(0xffffff26),
            ring: ColorToken::rgb(0x737373),
            success: ColorToken::rgb(0x4cdb7c),
            success_light: ColorToken::rgb(0x0c341e),
            warning: ColorToken::rgb(0xeab312),
            warning_light: ColorToken::rgb(0x432a08),
            danger: ColorToken::rgb(0xff6467),
            danger_light: ColorToken::rgb(0x451a1a),
            danger_foreground: ColorToken::rgb(0x2a0a0c),
            selection: ColorToken::rgba(0xe05a7233),
            scrim: ColorToken::rgba(0x05050599),
            decor_line: ColorToken::rgb(0x737373),
            hilite: ColorToken::rgba(0x00000000),
            glow: ColorToken::rgba(0x00000000),
            brand: accent_tokens.brand,
            brand_hover: accent_tokens.brand_hover,
            brand_light: accent_tokens.brand_light,
            brand_foreground: accent_tokens.brand_foreground,
            shape,
            decor,
        },
    }
}
